module.exports = {
  User: require('./User'),
  Institution: require('./Institution'),
  InstitutionApplication: require('./InstitutionApplication'),
  Affidavit: require('./Affidavit'),
  FieldInspection: require('./FieldInspection'),
  Committee: require('./Committee'),
  CouncilMeeting: require('./CouncilMeeting'),
  Student: require('./Student'),
  StudentAttendance: require('./StudentAttendance'),
  Faculty: require('./Faculty'),
  FacultyAttendance: require('./FacultyAttendance'),
  Payment: require('./Payment'),
  Renewal: require('./Renewal'),
  Notification: require('./Notification'),
  AuditLog: require('./AuditLog'),
  Document: require('./Document'),
  BiometricDevice: require('./BiometricDevice'),
  BiometricEvent: require('./BiometricEvent'),
  CameraStream: require('./CameraStream'),
};
