const ROLES = {
  SUPER_ADMIN: 'super_admin',
  COUNCIL_MEMBER: 'council_member',
  COMMITTEE_MEMBER: 'committee_member',
  FIELD_OFFICER: 'field_officer',
  INSTITUTION_ADMIN: 'institution_admin',
  PRINCIPAL: 'principal',
  FACULTY: 'faculty',
  STUDENT: 'student',
  FINANCE_OFFICER: 'finance_officer',
  MONITORING_OFFICER: 'monitoring_officer',
};

const PERMISSIONS = {
  // Users
  USERS_READ: 'users:read',
  USERS_CREATE: 'users:create',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',

  // Institutions
  INSTITUTIONS_READ: 'institutions:read',
  INSTITUTIONS_CREATE: 'institutions:create',
  INSTITUTIONS_UPDATE: 'institutions:update',
  INSTITUTIONS_APPROVE: 'institutions:approve',
  INSTITUTIONS_SUSPEND: 'institutions:suspend',

  // Affidavits
  AFFIDAVITS_READ: 'affidavits:read',
  AFFIDAVITS_CREATE: 'affidavits:create',
  AFFIDAVITS_VERIFY: 'affidavits:verify',
  AFFIDAVITS_APPROVE: 'affidavits:approve',

  // Field Inspections
  INSPECTIONS_READ: 'inspections:read',
  INSPECTIONS_CREATE: 'inspections:create',
  INSPECTIONS_SUBMIT: 'inspections:submit',
  INSPECTIONS_ASSIGN: 'inspections:assign',

  // Committees
  COMMITTEES_READ: 'committees:read',
  COMMITTEES_MANAGE: 'committees:manage',
  COMMITTEES_VOTE: 'committees:vote',
  COMMITTEES_REVIEW: 'committees:review',

  // Council
  COUNCIL_READ: 'council:read',
  COUNCIL_APPROVE: 'council:approve',
  COUNCIL_RESOLUTION: 'council:resolution',

  // Students
  STUDENTS_READ: 'students:read',
  STUDENTS_CREATE: 'students:create',
  STUDENTS_UPDATE: 'students:update',
  STUDENTS_APPROVE: 'students:approve',
  STUDENTS_RENEW: 'students:renew',

  // Faculty
  FACULTY_READ: 'faculty:read',
  FACULTY_CREATE: 'faculty:create',
  FACULTY_UPDATE: 'faculty:update',
  FACULTY_APPROVE: 'faculty:approve',
  FACULTY_RENEW: 'faculty:renew',

  // Attendance
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_MANAGE: 'attendance:manage',
  ATTENDANCE_ADJUST: 'attendance:adjust',

  // Biometric
  BIOMETRIC_READ: 'biometric:read',
  BIOMETRIC_MANAGE: 'biometric:manage',

  // Monitoring
  MONITORING_READ: 'monitoring:read',
  MONITORING_STREAM: 'monitoring:stream',
  MONITORING_CAPTURE: 'monitoring:capture',

  // Payments
  PAYMENTS_READ: 'payments:read',
  PAYMENTS_CREATE: 'payments:create',
  PAYMENTS_VERIFY: 'payments:verify',
  PAYMENTS_REFUND: 'payments:refund',

  // Notifications
  NOTIFICATIONS_READ: 'notifications:read',
  NOTIFICATIONS_SEND: 'notifications:send',

  // Audit
  AUDIT_READ: 'audit:read',

  // Documents
  DOCUMENTS_READ: 'documents:read',
  DOCUMENTS_UPLOAD: 'documents:upload',
  DOCUMENTS_DELETE: 'documents:delete',

  // Dashboard
  DASHBOARD_ADMIN: 'dashboard:admin',
  DASHBOARD_INSTITUTION: 'dashboard:institution',
  DASHBOARD_FIELD: 'dashboard:field',
  DASHBOARD_COMMITTEE: 'dashboard:committee',
  DASHBOARD_COUNCIL: 'dashboard:council',
  DASHBOARD_MONITORING: 'dashboard:monitoring',
  DASHBOARD_FINANCE: 'dashboard:finance',
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.COUNCIL_MEMBER]: [
    PERMISSIONS.COUNCIL_READ,
    PERMISSIONS.COUNCIL_APPROVE,
    PERMISSIONS.COUNCIL_RESOLUTION,
    PERMISSIONS.INSTITUTIONS_READ,
    PERMISSIONS.INSTITUTIONS_APPROVE,
    PERMISSIONS.INSTITUTIONS_SUSPEND,
    PERMISSIONS.AFFIDAVITS_READ,
    PERMISSIONS.AFFIDAVITS_APPROVE,
    PERMISSIONS.COMMITTEES_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_APPROVE,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.FACULTY_APPROVE,
    PERMISSIONS.INSPECTIONS_READ,
    PERMISSIONS.DASHBOARD_COUNCIL,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.DOCUMENTS_READ,
  ],

  [ROLES.COMMITTEE_MEMBER]: [
    PERMISSIONS.COMMITTEES_READ,
    PERMISSIONS.COMMITTEES_VOTE,
    PERMISSIONS.COMMITTEES_REVIEW,
    PERMISSIONS.INSTITUTIONS_READ,
    PERMISSIONS.AFFIDAVITS_READ,
    PERMISSIONS.AFFIDAVITS_VERIFY,
    PERMISSIONS.INSPECTIONS_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_APPROVE,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.DASHBOARD_COMMITTEE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.DOCUMENTS_READ,
  ],

  [ROLES.FIELD_OFFICER]: [
    PERMISSIONS.INSPECTIONS_READ,
    PERMISSIONS.INSPECTIONS_CREATE,
    PERMISSIONS.INSPECTIONS_SUBMIT,
    PERMISSIONS.INSTITUTIONS_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.DASHBOARD_FIELD,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],

  [ROLES.INSTITUTION_ADMIN]: [
    PERMISSIONS.INSTITUTIONS_READ,
    PERMISSIONS.INSTITUTIONS_UPDATE,
    PERMISSIONS.INSTITUTIONS_CREATE,
    PERMISSIONS.AFFIDAVITS_CREATE,
    PERMISSIONS.AFFIDAVITS_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_UPDATE,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.FACULTY_CREATE,
    PERMISSIONS.FACULTY_UPDATE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.STUDENTS_RENEW,
    PERMISSIONS.FACULTY_RENEW,
    PERMISSIONS.DASHBOARD_INSTITUTION,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_UPLOAD,
  ],

  [ROLES.PRINCIPAL]: [
    PERMISSIONS.INSTITUTIONS_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_UPDATE,
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.FACULTY_CREATE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.DASHBOARD_INSTITUTION,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_UPLOAD,
  ],

  [ROLES.FACULTY]: [
    PERMISSIONS.FACULTY_READ,
    PERMISSIONS.FACULTY_UPDATE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.FACULTY_RENEW,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.STUDENTS_RENEW,
  ],

  [ROLES.FINANCE_OFFICER]: [
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_VERIFY,
    PERMISSIONS.PAYMENTS_REFUND,
    PERMISSIONS.DASHBOARD_FINANCE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.AUDIT_READ,
  ],

  [ROLES.MONITORING_OFFICER]: [
    PERMISSIONS.MONITORING_READ,
    PERMISSIONS.MONITORING_STREAM,
    PERMISSIONS.MONITORING_CAPTURE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.INSTITUTIONS_READ,
    PERMISSIONS.DASHBOARD_MONITORING,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.BIOMETRIC_READ,
  ],
};

const INSTITUTION_TYPES = [
  'school_of_nursing',
  'college_of_nursing',
  'midwifery_school',
  'public_health_school',
];

const INSTITUTION_STATUSES = [
  'draft',
  'submitted',
  'under_review',
  'field_inspection_pending',
  'committee_review',
  'council_review',
  'approved',
  'rejected',
  'suspended',
  'expired',
];

const COMMITTEE_TYPES = [
  'academic',
  'selection',
  'discipline',
  'social',
  'finance',
  'inspection',
];

const PAYMENT_TYPES = [
  'student_registration',
  'student_renewal',
  'faculty_registration',
  'faculty_renewal',
  'institution_registration',
  'institution_renewal',
];

const PAYMENT_GATEWAYS = ['stripe', 'easypaisa', 'jazzcash'];

const BIOMETRIC_VENDORS = ['zkteco', 'essl', 'suprema'];

const ATTENDANCE_SOURCES = ['biometric', 'face_recognition', 'manual'];

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  INSTITUTION_TYPES,
  INSTITUTION_STATUSES,
  COMMITTEE_TYPES,
  PAYMENT_TYPES,
  PAYMENT_GATEWAYS,
  BIOMETRIC_VENDORS,
  ATTENDANCE_SOURCES,
};
